language: python
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install -d
  - pipenv install codecov
# command to run tests
script:
  - pipenv run coverage run --source limiter  -m unittest discover
after_success:
  - pipenv run codecov
services:
  - redis-server
